src/ts3_watcher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("ts3_watcher.web_ui.urls", namespace="web_ui")),
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/ts3_watcher/web_ui/urls.py
from django.urls import path

from . import views

app_name = "web_ui"
urlpatterns = (
    path("", views.IndexView.as_view(), name="index"),
    path("top/", views.TopUsersByTimeView.as_view(), name="top_alltime"),
    path("top/<int:year>/", views.TopUsersByTimeView.as_view(scope="year"), name="top_yearly"),
    path("top/<int:year>/<int:month>/", views.TopUsersByTimeView.as_view(scope="month"), name="top_monthly"),
    path("top/<int:year>/<int:month>/<int:day>/", views.TopUsersByTimeView.as_view(scope="day"), name="top_daily"),
)

src/ts3_watcher/processing/models/user_connection.py
from django.db import models

from ts3_watcher.processing.querysets import UserConnectionManager


class UserConnection(models.Model):
    user_id = models.IntegerField(db_index=True)
    user_nickname = models.CharField(max_length=255)
    connected_at = models.DateTimeField(db_index=True)
    disconnected_at = models.DateTimeField(db_index=True)

    objects = UserConnectionManager()

    def __str__(self):
        return f"UserConnection({self.user_id}, {str(self.connected_at)}, {str(self.disconnected_at)})"

src/ts3_watcher/web_ui/views/index.py
from datetime import datetime

from django.conf import settings
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from ts3_watcher.core.query import ts3_connection
from ts3_watcher.utils import channel_tree


class IndexView(TemplateView):
    template_name = "web_ui/index.html"

    @method_decorator(cache_page(settings.PAGE_CACHE_TIME))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.method == "OPTIONS":
            return context

        with ts3_connection() as query:
            # Get lists of channels and active clients
            channels = query.exec_("channellist", "flags", "icon").parsed
            clients = query.exec_("clientlist", "away", "voice").parsed

            # Get every client from the database (active and inactive)
            db_client_count = query.exec_("clientdblist", "count").parsed[0]["count"]
            db_clients = query.exec_("clientdblist", duration=db_client_count).parsed

        # Filter out server query clients
        clients = [cl for cl in clients if cl["client_type"] == "0"]

        # Filter out clients that are already online
        db_clients = [
            dbcl for dbcl in db_clients
            if not any(cl["client_database_id"] == dbcl["cldbid"] for cl in clients)
        ]

        # Sort clients by last connected time
        db_clients = sorted(
            db_clients,
            key=lambda cl: datetime.fromtimestamp(int(cl["client_lastconnected"])),
            reverse=True,
        )

        context.update(
            timestamp=timezone.now(),
            channel_tree=channel_tree(channels, clients),
            recent_logins=db_clients[:settings.TS3_RECENT_LENGTH],
        )

        return context

src/ts3_watcher/web_ui/views/top_time.py
import calendar
from datetime import datetime

from django.utils import timezone
from django.views.generic import TemplateView

from ts3_watcher.processing.models import UserConnection


class TopUsersByTimeView(TemplateView):
    template_name = "web_ui/top_time.html"
    scope = None  # overwritten in urlpatterns

    def get_date_range(self):
        year = self.kwargs.get("year")
        month = self.kwargs.get("month")
        day = self.kwargs.get("day")

        match self.scope:
            case "year":
                begin = datetime(year=year, month=1, day=1)
                end = datetime.combine(datetime(year=year, month=12, day=31), datetime.max.time())

            case "month":
                _, last_day = calendar.monthrange(year, month)
                begin = datetime(year=year, month=month, day=1)
                end = datetime.combine(datetime(year=year, month=month, day=last_day), datetime.max.time())

            case "day":
                begin = datetime(year=year, month=month, day=day)
                end = datetime.combine(begin, datetime.max.time())

            case _:
                return None, None

        begin = timezone.make_aware(begin)
        end = timezone.make_aware(end)

        return begin, end

    def get_date_scroll_iters(self, lb: datetime, ub: datetime) -> dict:
        year = self.kwargs.get("year")
        month = self.kwargs.get("month")

        iters = {
            "years": range(lb.year, ub.year + 1),
        }

        if self.scope in ("year", "month", "day"):
            lbm = lb.month if lb.year == year else 1
            ubm = ub.month if ub.year == year else 12
            iters["months"] = range(lbm, ubm + 1)

        if self.scope in ("month", "day"):
            _, last_day = calendar.monthrange(ub.year, ub.month)
            lbd = lb.day if lb.year == year and lb.month == month else 1
            ubd = ub.day if ub.year == year and ub.month == month else last_day
            iters["days"] = range(lbd, ubd + 1)

        return iters

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        qs = UserConnection.objects.all()

        global_bounds = qs.aggregate_dt_boundaries()
        scope_bounds = global_bounds

        scroll_iters = self.get_date_scroll_iters(
            global_bounds["since"],
            global_bounds["until"]
        )

        scope_begin, scope_end = self.get_date_range()

        if scope_begin and scope_end:
            qs = qs.filter_between(scope_begin, scope_end)
            scope_bounds = qs.aggregate_dt_boundaries()

        top_users = qs.group_top_users()[:10]

        user_ids = [top["user_id"] for top in top_users]

        nicknames_qs = qs.group_last_user_nicknames(user_ids)
        nicknames = {user["user_id"]: user["user_nickname"] for user in list(nicknames_qs)}

        for top in top_users:
            top["user_nickname"] = nicknames.get(top.get("user_id"))
            top["total_hours"] = round(top["total_connection_time"].total_seconds() / 3600)

        context.update(
            scope=self.scope,
            global_bounds=global_bounds,
            scope_bounds=scope_bounds,
            scroll_iters=scroll_iters,
            scope_begin=scope_begin,
            scope_end=scope_end,
            top_users=top_users,
        )

        return context

src/ts3_watcher/web_ui/templates/web_ui/_base.html
{% load static %}
{% load i18n %}

{% get_language_info for LANGUAGE_CODE as lang %}

<!DOCTYPE html>
<html lang="{{ lang.code }}" data-bs-theme="dark">
<head>
  {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  {% endblock %}
  {% block title %}
    <title>{{ ts3.server_info.virtualserver_name }}</title>
  {% endblock %}
  {% block styles %}
    <link rel="stylesheet" href="{% static "bs5/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "bs5/bootstrap-icons.min.css" %}">
    <link rel="stylesheet" href="{% static "web_ui/css/style.css" %}">
  {% endblock %}
</head>

<body>
{% block body %}
  <nav class="navbar navbar-expand-lg bg-body-secondary">
    <div class="container">
      <span class="navbar-brand">
        <i class="icon i-vserver"></i>

        <span class="fw-bold">
          {{ ts3.server_info.virtualserver_name }}
        </span>
      </span>

      <button
        type="button"
        class="navbar-toggler" 
        data-bs-toggle="collapse"
        data-bs-target="#navbar"
        aria-controls="navbar"
        aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav me-auto my-2 my-lg-0 ps-2">
          {% with request.path as current_url %}
            <li class="nav-item">
              {% url "web_ui:index" as index_url %}
              <a href="{{ index_url }}" class="nav-link {% if current_url == index_url %}active{% endif %}">
                <i class="bi bi-house"></i>
                {% trans "Homepage" %}
              </a>
            </li>

            <li class="nav-item">
              {% url "web_ui:top_alltime" as top_users_page %}
              <a href="{{ top_users_page }}" class="nav-link {% if current_url == top_users_page %}active{% endif %}">
                <i class="bi bi-clock-history"></i>
                {% trans "Top users" %}
              </a>
            </li>
          {% endwith %}

          <li class="nav-item my-auto">
            <div class="d-flex">
              <i class="bi bi-lightbulb"></i>

              <div class="form-check form-switch ps-5">
                <input class="form-check-input" type="checkbox" role="switch" id="theme-switcher">
                <label class="form-check-label d-none" for="theme-switcher">
                  {% trans "Switch theme" %}
                </label>
              </div>

              <i class="bi bi-lightbulb-fill"></i>
            </div>
          </li>
        </ul>

        {% if ts3.public_addr %}
          <form method="get" action="{{ ts3.public_addr }}" class="d-flex justify-content-center">
            <button type="submit" class="btn btn-outline-secondary rounded-0">
              {% trans "Join server" %}
            </button>
          </form>
        {% endif %}
      </div>
    </div>
  </nav>

  <main>
    {% block main %}
      <p class="text-center">
        Extend me!
      </p>
    {% endblock %}
  </main>

  <footer class="text-center text-lg-start text-muted">
    {% block footer %}
    {% endblock %}
  </footer>
{% endblock %}

{% block scripts %}
  <script src="{% static "bs5/bootstrap.bundle.min.js" %}" defer></script>
  <script src="{% static "web_ui/js/theme.js" %}" defer></script>
{% endblock %}
</body>
</html>

src/ts3_watcher/web_ui/templates/web_ui/_partial/item_channel_tree.html
{% load web_ui %}

<li class="list-group-item">
  <span class="fw-bold">
    <i class="icon {{ channel | channel_icon }}"></i>
    {{ channel.channel_name }}
  </span>

  {% if channel.subchannels or channel.clients %}
    <ul class="list-group list-group-flush">
      {% for subchannel in channel.subchannels %}
        {% include "web_ui/_partial/item_channel_tree.html" with channel=subchannel only %}
      {% endfor %}

      {% for client in channel.clients %}
        <li class="list-group-item border-0 py-0">
          <i class="icon {{ client | client_icon }}"></i>
          {{ client.client_nickname }}
        </li>
      {% endfor %}
    </ul>
  {% endif %}
</li>

src/ts3_watcher/web_ui/templates/web_ui/_partial/item_recent_conn.html
{% load humanize %}
{% load web_ui %}

<li class="list-group-item d-flex justify-content-between align-items-start mb-3">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-sm-6 mx-0 text-truncate">
        {{ db_client.client_nickname }}
      </div>

      <div class="col-12 col-sm-6 mx-0 text-start text-sm-end fw-lighter">
        {{ db_client.client_lastconnected | ts_date | naturaltime }}
      </div>
    </div>

    <div class="row d-none d-md-block">
      <div class="col-12 fw-lighter mx-0">
        {{ db_client.client_lastconnected | ts_date | date:"Y-m-d H:i:s" }}
      </div>
    </div>
  </div>
</li>

src/ts3_watcher/web_ui/templates/web_ui/index.html
{% extends "web_ui/_base.html" %}

{% load humanize %}
{% load i18n %}
{% load static %}

{% block main %}
  <div class="container py-2">
    <div class="row">
      {# Active users #}
      <div class="col-12 col-lg-6 mb-4">
        <div class="card rounded-0 h-100">
          <div class="card-header d-flex justify-content-between">
            <h5 class="card-title mb-0">
              {% trans "Active users" %}
            </h5>
          </div>

          {% if channel_tree %}
            <div class="card-body">
              <ul class="list-group list-group-flush">
                {% for channel in channel_tree %}
                  {% include "web_ui/_partial/item_channel_tree.html" with channel=channel only %}
                {% endfor %}
              </ul>
            </div>
          {% else %}
            <img
              class="img-fluid"
              src="{% static "web_ui/img/empty_server.gif" %}"
              alt="{% trans "Server is empty" %}"/>

            <div class="card-body h-100 d-flex flex-column justify-content-center align-items-center">
              <p class="card-text">
                {% trans "Nobody's here yet." %}
              </p>

              <a href="{{ server_join_url }}">
                {% trans "Be the first one!" %}
              </a>
            </div>
          {% endif %}
        </div>
      </div>

      {# Recent connections #}
      <div class="col-12 col-lg-6 mb-4">
        <div class="card rounded-0 h-100">
          <div class="card-header">
            <h5 class="card-title mb-0">
              {% trans "Recent connections" %}
            </h5>
          </div>

          <div class="card-body">
            <ul class="list-group-flush ps-0 bottom-fadeout">
              {% for db_client in recent_logins %}
                {% include "web_ui/_partial/item_recent_conn.html" with db_client=db_client only %}
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block footer %}
  <div class="container">
    <p class="small">
      {% trans "Snapshot at" %}
      {{ timestamp | date:"Y-m-d H:i:s" }}
    </p>
  </div>
{% endblock %}

src/ts3_watcher/web_ui/templates/web_ui/top_time.html
{% extends "web_ui/_base.html" %}

{% load humanize %}
{% load i18n %}
{% load static %}

{% block main %}
  <div class="container py-2">
    <div class="row">
      <div class="d-flex justify-content-evenly">
        {% for y in scroll_iters.years %}
          <a href="{% url "web_ui:top_yearly" y %}"
             class="btn{% if y == year %} active{% endif %}">
            Y{{ y }}
          </a>
        {% endfor %}
      </div>
    </div>

    <hr/>

    {% if scroll_iters.months %}
      <div class="row">
        <div class="d-flex justify-content-evenly">
          {% for m in scroll_iters.months %}
            <a href="{% url "web_ui:top_monthly" year m %}"
               class="btn{% if m == month %} active{% endif %}">
              M{{ m }}
            </a>
          {% endfor %}
        </div>
      </div>

      <hr/>
    {% endif %}

    {% if scroll_iters.days %}
      <div class="row d-flex flex-wrap">
        <div class="justify-content-evenly">
          {% for d in scroll_iters.days %}
            <a href="{% url "web_ui:top_daily" year month d %}"
               class="btn{% if d == day %} active{% endif %}">
              D{{ d }}
            </a>
          {% endfor %}
        </div>
      </div>

      <hr/>
    {% endif %}

    <div class="row">
      <div class="col-12">
        {% if top_users %}
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
              <tr>
                <th></th>
                <th>{% trans "User" %}</th>
                <th>{% trans "Total hours" %}</th>
              </tr>
              </thead>

              <tbody>
              {% for user in top_users %}
                <tr>
                  <td>
                    {% with forloop.counter as n %}
                      {{ n }}.
                    {% endwith %}
                  </td>
                  <td>{{ user.user_nickname }}</td>
                  <td>{{ user.total_hours }} h</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div class="alert alert-info text-center" role="alert">
            {% trans "No data" %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

{% block footer %}
  <div class="container">
    <p class="small">
      {% trans "Data since" %}
      {{ scope_bounds.since | date:"Y-m-d H:i:s" | default:"N/A" }}
      {% trans "until" %}
      {{ scope_bounds.until | date:"Y-m-d H:i:s" | default:"N/A" }}
    </p>
  </div>
{% endblock %}